version: "3.8"

services:
  lovelystay:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lovelystay
    volumes:
      - postgres-data:/var/lib/postgresql/data
  lovelystay-test:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lovelystay
    volumes:
      - postgres-data-test:/var/lib/postgresql/data

volumes:
  postgres-data:
  postgres-data-test:
